# Advanced Analytics

## Objective
Perform advanced analysis on investor transactions and fund data.

## Analysis Covered
- Transaction statistics
- Investor behaviour
- Risk insights
- Fund comparison

In [1]:
import pandas as pd

trans = pd.read_csv("../data/processed/08_investor_transactions_clean.csv")

print("Shape:", trans.shape)

trans.head()

Shape: (32778, 13)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,Sip,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,Sip,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,Sip,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [2]:
trans.describe()

           amfi_code     amount_inr  annual_income_lakh
count   32778.000000   32778.000000        32778.000000
mean   120264.617518  107437.318628           26.181219
std     14370.205345  150415.905084           20.805425
min    100016.000000     400.000000            3.000000
25%    118632.000000    3153.000000           10.600000
50%    119551.000000   17782.500000           19.700000
75%    120843.000000  189324.250000           37.400000
max    149324.000000  597498.000000           99.700000

In [3]:
trans.describe()

           amfi_code     amount_inr  annual_income_lakh
count   32778.000000   32778.000000        32778.000000
mean   120264.617518  107437.318628           26.181219
std     14370.205345  150415.905084           20.805425
min    100016.000000     400.000000            3.000000
25%    118632.000000    3153.000000           10.600000
50%    119551.000000   17782.500000           19.700000
75%    120843.000000  189324.250000           37.400000
max    149324.000000  597498.000000           99.700000

In [4]:
print("Advanced Analytics Completed Successfully")

Advanced Analytics Completed Successfully